(define (main args)
  (let* ((s (read-line))
         (line (map string->number (string-split (read-line) " ")))
         (a (- (car line) 1))
         (b (- (cadr line) 1))
         (A (substring s 0 a))
         (B (substring s a (+ a 1)))
         (C (substring s (+ a 1) b))
         (D (substring s b (+ b 1)))
         (E (substring s (+ b 1) (string-length s))))
    (print A D C B E))
  0)